### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by kts707** [jasonyzhang/relpose#1]
Hi Jason,

Thanks for the great work! When will the code be released?

**Comment by jasonyzhang** [comment]
Hi,

Thanks for your interest.

The plan is to have a demo released soon (by ECCV) and the training code once I have a bit more bandwidth. The models are currently trained on CO3Dv1, and I want to make sure that we have replicable models trained on CO3Dv2.

If you need to run the code for anything time sensitive, send me an email and I can give you an internal release.

Best,
Jason

**Comment by kts707** [comment]
Hi Jason,

Thanks for the quick response! I just sent you an email on this. 

Best,
Chris
